package faa.travel.agency.ontology.classes;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: Customer <br>
 * @version generated on Mon Apr 17 12:31:16 BST 2017 by favina
 */

public interface Customer extends Person {

    /* ***************************************************
     * Property http://www.le.ac.uk/travelAgencyOntology.owl#canPay
     */
     
    /**
     * Gets all property values for the canPay property.<p>
     * 
     * @returns a collection of values for the canPay property.
     */
    Collection<? extends Package> getCanPay();

    /**
     * Checks if the class has a canPay property value.<p>
     * 
     * @return true if there is a canPay property value.
     */
    boolean hasCanPay();

    /**
     * Adds a canPay property value.<p>
     * 
     * @param newCanPay the canPay property value to be added
     */
    void addCanPay(Package newCanPay);

    /**
     * Removes a canPay property value.<p>
     * 
     * @param oldCanPay the canPay property value to be removed.
     */
    void removeCanPay(Package oldCanPay);


    /* ***************************************************
     * Property http://www.le.ac.uk/travelAgencyOntology.owl#isCategorized
     */
     
    /**
     * Gets all property values for the isCategorized property.<p>
     * 
     * @returns a collection of values for the isCategorized property.
     */
    Collection<? extends Customer_Type> getIsCategorized();

    /**
     * Checks if the class has a isCategorized property value.<p>
     * 
     * @return true if there is a isCategorized property value.
     */
    boolean hasIsCategorized();

    /**
     * Adds a isCategorized property value.<p>
     * 
     * @param newIsCategorized the isCategorized property value to be added
     */
    void addIsCategorized(Customer_Type newIsCategorized);

    /**
     * Removes a isCategorized property value.<p>
     * 
     * @param oldIsCategorized the isCategorized property value to be removed.
     */
    void removeIsCategorized(Customer_Type oldIsCategorized);


    /* ***************************************************
     * Property http://www.le.ac.uk/travelAgencyOntology.owl#reserve
     */
     
    /**
     * Gets all property values for the reserve property.<p>
     * 
     * @returns a collection of values for the reserve property.
     */
    Collection<? extends Package> getReserve();

    /**
     * Checks if the class has a reserve property value.<p>
     * 
     * @return true if there is a reserve property value.
     */
    boolean hasReserve();

    /**
     * Adds a reserve property value.<p>
     * 
     * @param newReserve the reserve property value to be added
     */
    void addReserve(Package newReserve);

    /**
     * Removes a reserve property value.<p>
     * 
     * @param oldReserve the reserve property value to be removed.
     */
    void removeReserve(Package oldReserve);


    /* ***************************************************
     * Property http://www.le.ac.uk/travelAgencyOntology.owl#select
     */
     
    /**
     * Gets all property values for the selects property.<p>
     * 
     * @returns a collection of values for the selects property.
     */
    Collection<? extends City> getSelect();

    /**
     * Checks if the class has a selects property value.<p>
     * 
     * @return true if there is a selects property value.
     */
    boolean hasSelect();

    /**
     * Adds a selects property value.<p>
     * 
     * @param newSelects the selects property value to be added
     */
    void addSelect(City newSelect);

    /**
     * Removes a selects property value.<p>
     * 
     * @param oldSelects the selects property value to be removed.
     */
    void removeSelect(City oldSelect);


    /* ***************************************************
     * Property http://www.le.ac.uk/travelAgencyOntology.owl#Cust_ID
     */
     
    /**
     * Gets all property values for the Cust_ID property.<p>
     * 
     * @returns a collection of values for the Cust_ID property.
     */
    Collection<? extends Integer> getCust_ID();

    /**
     * Checks if the class has a Cust_ID property value.<p>
     * 
     * @return true if there is a Cust_ID property value.
     */
    boolean hasCust_ID();

    /**
     * Adds a Cust_ID property value.<p>
     * 
     * @param newCust_ID the Cust_ID property value to be added
     */
    void addCust_ID(Integer newCust_ID);

    /**
     * Removes a Cust_ID property value.<p>
     * 
     * @param oldCust_ID the Cust_ID property value to be removed.
     */
    void removeCust_ID(Integer oldCust_ID);



    /* ***************************************************
     * Property http://www.le.ac.uk/travelAgencyOntology.owl#Person_Gender
     */
     
    /**
     * Gets all property values for the Person_Gender property.<p>
     * 
     * @returns a collection of values for the Person_Gender property.
     */
    Collection<? extends String> getPerson_Gender();

    /**
     * Checks if the class has a Person_Gender property value.<p>
     * 
     * @return true if there is a Person_Gender property value.
     */
    boolean hasPerson_Gender();

    /**
     * Adds a Person_Gender property value.<p>
     * 
     * @param newPerson_Gender the Person_Gender property value to be added
     */
    void addPerson_Gender(String newPerson_Gender);

    /**
     * Removes a Person_Gender property value.<p>
     * 
     * @param oldPerson_Gender the Person_Gender property value to be removed.
     */
    void removePerson_Gender(String oldPerson_Gender);



    /* ***************************************************
     * Property http://www.le.ac.uk/travelAgencyOntology.owl#Person_Name
     */
     
    /**
     * Gets all property values for the Person_Name property.<p>
     * 
     * @returns a collection of values for the Person_Name property.
     */
    Collection<? extends String> getPerson_Name();

    /**
     * Checks if the class has a Person_Name property value.<p>
     * 
     * @return true if there is a Person_Name property value.
     */
    boolean hasPerson_Name();

    /**
     * Adds a Person_Name property value.<p>
     * 
     * @param newPerson_Name the Person_Name property value to be added
     */
    void addPerson_Name(String newPerson_Name);

    /**
     * Removes a Person_Name property value.<p>
     * 
     * @param oldPerson_Name the Person_Name property value to be removed.
     */
    void removePerson_Name(String oldPerson_Name);



    /* ***************************************************
     * Property http://www.le.ac.uk/travelAgencyOntology.owl#Person_dob
     */
     
    /**
     * Gets all property values for the Person_dob property.<p>
     * 
     * @returns a collection of values for the Person_dob property.
     */
    Collection<? extends String> getPerson_dob();

    /**
     * Checks if the class has a Person_dob property value.<p>
     * 
     * @return true if there is a Person_dob property value.
     */
    boolean hasPerson_dob();

    /**
     * Adds a Person_dob property value.<p>
     * 
     * @param newPerson_dob the Person_dob property value to be added
     */
    void addPerson_dob(String newPerson_dob);

    /**
     * Removes a Person_dob property value.<p>
     * 
     * @param oldPerson_dob the Person_dob property value to be removed.
     */
    void removePerson_dob(String oldPerson_dob);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
