package faa.travel.agency.ontology.classes;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: Monument <br>
 * @version generated on Mon Apr 17 12:31:16 BST 2017 by favina
 */

public interface Monument extends Attraction {

    /* ***************************************************
     * Property http://www.le.ac.uk/travelAgencyOntology.owl#recommend
     */
     
    /**
     * Gets all property values for the recommend property.<p>
     * 
     * @returns a collection of values for the recommend property.
     */
    Collection<? extends Activity> getRecommend();

    /**
     * Checks if the class has a recommend property value.<p>
     * 
     * @return true if there is a recommend property value.
     */
    boolean hasRecommend();

    /**
     * Adds a recommend property value.<p>
     * 
     * @param newRecommend the recommend property value to be added
     */
    void addRecommend(Activity newRecommend);

    /**
     * Removes a recommend property value.<p>
     * 
     * @param oldRecommend the recommend property value to be removed.
     */
    void removeRecommend(Activity oldRecommend);


    /* ***************************************************
     * Property http://www.le.ac.uk/travelAgencyOntology.owl#Attraction_Location
     */
     
    /**
     * Gets all property values for the Attraction_Location property.<p>
     * 
     * @returns a collection of values for the Attraction_Location property.
     */
    Collection<? extends String> getAttraction_Location();

    /**
     * Checks if the class has a Attraction_Location property value.<p>
     * 
     * @return true if there is a Attraction_Location property value.
     */
    boolean hasAttraction_Location();

    /**
     * Adds a Attraction_Location property value.<p>
     * 
     * @param newAttraction_Location the Attraction_Location property value to be added
     */
    void addAttraction_Location(String newAttraction_Location);

    /**
     * Removes a Attraction_Location property value.<p>
     * 
     * @param oldAttraction_Location the Attraction_Location property value to be removed.
     */
    void removeAttraction_Location(String oldAttraction_Location);



    /* ***************************************************
     * Property http://www.le.ac.uk/travelAgencyOntology.owl#Attraction_Name
     */
     
    /**
     * Gets all property values for the Attraction_Name property.<p>
     * 
     * @returns a collection of values for the Attraction_Name property.
     */
    Collection<? extends String> getAttraction_Name();

    /**
     * Checks if the class has a Attraction_Name property value.<p>
     * 
     * @return true if there is a Attraction_Name property value.
     */
    boolean hasAttraction_Name();

    /**
     * Adds a Attraction_Name property value.<p>
     * 
     * @param newAttraction_Name the Attraction_Name property value to be added
     */
    void addAttraction_Name(String newAttraction_Name);

    /**
     * Removes a Attraction_Name property value.<p>
     * 
     * @param oldAttraction_Name the Attraction_Name property value to be removed.
     */
    void removeAttraction_Name(String oldAttraction_Name);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
