package faa.travel.agency.ontology.classes;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: Package <br>
 * @version generated on Mon Apr 17 12:31:16 BST 2017 by favina
 */

public interface Package extends WrappedIndividual {

    /* ***************************************************
     * Property http://www.le.ac.uk/travelAgencyOntology.owl#Incoporate
     */
     
    /**
     * Gets all property values for the Incoporate property.<p>
     * 
     * @returns a collection of values for the Incoporate property.
     */
    Collection<? extends Budget> getIncoporate();

    /**
     * Checks if the class has a Incoporate property value.<p>
     * 
     * @return true if there is a Incoporate property value.
     */
    boolean hasIncoporate();

    /**
     * Adds a Incoporate property value.<p>
     * 
     * @param newIncoporate the Incoporate property value to be added
     */
    void addIncoporate(Budget newIncoporate);

    /**
     * Removes a Incoporate property value.<p>
     * 
     * @param oldIncoporate the Incoporate property value to be removed.
     */
    void removeIncoporate(Budget oldIncoporate);


    /* ***************************************************
     * Property http://www.le.ac.uk/travelAgencyOntology.owl#Pkg_Avalibility
     */
     
    /**
     * Gets all property values for the Pkg_Avalibility property.<p>
     * 
     * @returns a collection of values for the Pkg_Avalibility property.
     */
    Collection<? extends Integer> getPkg_Avalibility();

    /**
     * Checks if the class has a Pkg_Avalibility property value.<p>
     * 
     * @return true if there is a Pkg_Avalibility property value.
     */
    boolean hasPkg_Avalibility();

    /**
     * Adds a Pkg_Avalibility property value.<p>
     * 
     * @param newPkg_Avalibility the Pkg_Avalibility property value to be added
     */
    void addPkg_Avalibility(Integer newPkg_Avalibility);

    /**
     * Removes a Pkg_Avalibility property value.<p>
     * 
     * @param oldPkg_Avalibility the Pkg_Avalibility property value to be removed.
     */
    void removePkg_Avalibility(Integer oldPkg_Avalibility);



    /* ***************************************************
     * Property http://www.le.ac.uk/travelAgencyOntology.owl#Pkg_Detail
     */
     
    /**
     * Gets all property values for the Pkg_Detail property.<p>
     * 
     * @returns a collection of values for the Pkg_Detail property.
     */
    Collection<? extends String> getPkg_Detail();

    /**
     * Checks if the class has a Pkg_Detail property value.<p>
     * 
     * @return true if there is a Pkg_Detail property value.
     */
    boolean hasPkg_Detail();

    /**
     * Adds a Pkg_Detail property value.<p>
     * 
     * @param newPkg_Detail the Pkg_Detail property value to be added
     */
    void addPkg_Detail(String newPkg_Detail);

    /**
     * Removes a Pkg_Detail property value.<p>
     * 
     * @param oldPkg_Detail the Pkg_Detail property value to be removed.
     */
    void removePkg_Detail(String oldPkg_Detail);



    /* ***************************************************
     * Property http://www.le.ac.uk/travelAgencyOntology.owl#Pkg_Duration
     */
     
    /**
     * Gets all property values for the Pkg_Duration property.<p>
     * 
     * @returns a collection of values for the Pkg_Duration property.
     */
    Collection<? extends Integer> getPkg_Duration();

    /**
     * Checks if the class has a Pkg_Duration property value.<p>
     * 
     * @return true if there is a Pkg_Duration property value.
     */
    boolean hasPkg_Duration();

    /**
     * Adds a Pkg_Duration property value.<p>
     * 
     * @param newPkg_Duration the Pkg_Duration property value to be added
     */
    void addPkg_Duration(Integer newPkg_Duration);

    /**
     * Removes a Pkg_Duration property value.<p>
     * 
     * @param oldPkg_Duration the Pkg_Duration property value to be removed.
     */
    void removePkg_Duration(Integer oldPkg_Duration);



    /* ***************************************************
     * Property http://www.le.ac.uk/travelAgencyOntology.owl#Pkg_GuidedTour
     */
     
    /**
     * Gets all property values for the Pkg_GuidedTour property.<p>
     * 
     * @returns a collection of values for the Pkg_GuidedTour property.
     */
    Collection<? extends String> getPkg_GuidedTour();

    /**
     * Checks if the class has a Pkg_GuidedTour property value.<p>
     * 
     * @return true if there is a Pkg_GuidedTour property value.
     */
    boolean hasPkg_GuidedTour();

    /**
     * Adds a Pkg_GuidedTour property value.<p>
     * 
     * @param newPkg_GuidedTour the Pkg_GuidedTour property value to be added
     */
    void addPkg_GuidedTour(String newPkg_GuidedTour);

    /**
     * Removes a Pkg_GuidedTour property value.<p>
     * 
     * @param oldPkg_GuidedTour the Pkg_GuidedTour property value to be removed.
     */
    void removePkg_GuidedTour(String oldPkg_GuidedTour);



    /* ***************************************************
     * Property http://www.le.ac.uk/travelAgencyOntology.owl#Pkg_ID
     */
     
    /**
     * Gets all property values for the Pkg_ID property.<p>
     * 
     * @returns a collection of values for the Pkg_ID property.
     */
    Collection<? extends Integer> getPkg_ID();

    /**
     * Checks if the class has a Pkg_ID property value.<p>
     * 
     * @return true if there is a Pkg_ID property value.
     */
    boolean hasPkg_ID();

    /**
     * Adds a Pkg_ID property value.<p>
     * 
     * @param newPkg_ID the Pkg_ID property value to be added
     */
    void addPkg_ID(Integer newPkg_ID);

    /**
     * Removes a Pkg_ID property value.<p>
     * 
     * @param oldPkg_ID the Pkg_ID property value to be removed.
     */
    void removePkg_ID(Integer oldPkg_ID);



    /* ***************************************************
     * Property http://www.le.ac.uk/travelAgencyOntology.owl#Pkg_budget
     */
     
    /**
     * Gets all property values for the Pkg_budget property.<p>
     * 
     * @returns a collection of values for the Pkg_budget property.
     */
    Collection<? extends String> getPkg_budget();

    /**
     * Checks if the class has a Pkg_budget property value.<p>
     * 
     * @return true if there is a Pkg_budget property value.
     */
    boolean hasPkg_budget();

    /**
     * Adds a Pkg_budget property value.<p>
     * 
     * @param newPkg_budget the Pkg_budget property value to be added
     */
    void addPkg_budget(String newPkg_budget);

    /**
     * Removes a Pkg_budget property value.<p>
     * 
     * @param oldPkg_budget the Pkg_budget property value to be removed.
     */
    void removePkg_budget(String oldPkg_budget);



    /* ***************************************************
     * Property http://www.le.ac.uk/travelAgencyOntology.owl#Pkg_type
     */
     
    /**
     * Gets all property values for the Pkg_type property.<p>
     * 
     * @returns a collection of values for the Pkg_type property.
     */
    Collection<? extends String> getPkg_type();

    /**
     * Checks if the class has a Pkg_type property value.<p>
     * 
     * @return true if there is a Pkg_type property value.
     */
    boolean hasPkg_type();

    /**
     * Adds a Pkg_type property value.<p>
     * 
     * @param newPkg_type the Pkg_type property value to be added
     */
    void addPkg_type(String newPkg_type);

    /**
     * Removes a Pkg_type property value.<p>
     * 
     * @param oldPkg_type the Pkg_type property value to be removed.
     */
    void removePkg_type(String oldPkg_type);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
