package faa.travel.agency.ontology.classes;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: Person <br>
 * @version generated on Mon Apr 17 12:31:16 BST 2017 by favina
 */

public interface Person extends WrappedIndividual {

    /* ***************************************************
     * Property http://www.le.ac.uk/travelAgencyOntology.owl#Person_Gender
     */
     
    /**
     * Gets all property values for the Person_Gender property.<p>
     * 
     * @returns a collection of values for the Person_Gender property.
     */
    Collection<? extends String> getPerson_Gender();

    /**
     * Checks if the class has a Person_Gender property value.<p>
     * 
     * @return true if there is a Person_Gender property value.
     */
    boolean hasPerson_Gender();

    /**
     * Adds a Person_Gender property value.<p>
     * 
     * @param newPerson_Gender the Person_Gender property value to be added
     */
    void addPerson_Gender(String newPerson_Gender);

    /**
     * Removes a Person_Gender property value.<p>
     * 
     * @param oldPerson_Gender the Person_Gender property value to be removed.
     */
    void removePerson_Gender(String oldPerson_Gender);



    /* ***************************************************
     * Property http://www.le.ac.uk/travelAgencyOntology.owl#Person_Name
     */
     
    /**
     * Gets all property values for the Person_Name property.<p>
     * 
     * @returns a collection of values for the Person_Name property.
     */
    Collection<? extends String> getPerson_Name();

    /**
     * Checks if the class has a Person_Name property value.<p>
     * 
     * @return true if there is a Person_Name property value.
     */
    boolean hasPerson_Name();

    /**
     * Adds a Person_Name property value.<p>
     * 
     * @param newPerson_Name the Person_Name property value to be added
     */
    void addPerson_Name(String newPerson_Name);

    /**
     * Removes a Person_Name property value.<p>
     * 
     * @param oldPerson_Name the Person_Name property value to be removed.
     */
    void removePerson_Name(String oldPerson_Name);



    /* ***************************************************
     * Property http://www.le.ac.uk/travelAgencyOntology.owl#Person_dob
     */
     
    /**
     * Gets all property values for the Person_dob property.<p>
     * 
     * @returns a collection of values for the Person_dob property.
     */
    Collection<? extends String> getPerson_dob();

    /**
     * Checks if the class has a Person_dob property value.<p>
     * 
     * @return true if there is a Person_dob property value.
     */
    boolean hasPerson_dob();

    /**
     * Adds a Person_dob property value.<p>
     * 
     * @param newPerson_dob the Person_dob property value to be added
     */
    void addPerson_dob(String newPerson_dob);

    /**
     * Removes a Person_dob property value.<p>
     * 
     * @param oldPerson_dob the Person_dob property value to be removed.
     */
    void removePerson_dob(String oldPerson_dob);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
