package faa.travel.agency.ontology.classes;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: Place <br>
 * @version generated on Mon Apr 17 12:31:16 BST 2017 by favina
 */

public interface Place extends WrappedIndividual {

    /* ***************************************************
     * Property http://www.le.ac.uk/travelAgencyOntology.owl#recommend
     */
     
    /**
     * Gets all property values for the recommend property.<p>
     * 
     * @returns a collection of values for the recommend property.
     */
    Collection<? extends Activity> getRecommend();

    /**
     * Checks if the class has a recommend property value.<p>
     * 
     * @return true if there is a recommend property value.
     */
    boolean hasRecommend();

    /**
     * Adds a recommend property value.<p>
     * 
     * @param newRecommend the recommend property value to be added
     */
    void addRecommend(Activity newRecommend);

    /**
     * Removes a recommend property value.<p>
     * 
     * @param oldRecommend the recommend property value to be removed.
     */
    void removeRecommend(Activity oldRecommend);


    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
