package faa.travel.agency.ontology.classes;

import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLDataFactory;
import org.semanticweb.owlapi.model.OWLDataProperty;
import org.semanticweb.owlapi.model.OWLObjectProperty;

/**
 * Vocabulary class to provide access to the Manchester OWL API representatives for 
 * various entities in the ontology used to generate this code.<p> 
 * 
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: ${javaClass}
 *
 * @version generated on Mon Apr 17 12:31:15 BST 2017 by favina
 */

public class Vocabulary {

	private static final OWLDataFactory factory = OWLManager.createOWLOntologyManager().getOWLDataFactory();

    /* ***************************************************
     * Class http://www.le.ac.uk/travelAgencyOntology.owl#Accomodation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ACCOMODATION.<p>
     * 
     */
    public static final OWLClass CLASS_ACCOMODATION = factory.getOWLClass(IRI.create("http://www.le.ac.uk/travelAgencyOntology.owl#Accomodation"));

    /* ***************************************************
     * Class http://www.le.ac.uk/travelAgencyOntology.owl#Activity
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ACTIVITY.<p>
     * 
     */
    public static final OWLClass CLASS_ACTIVITY = factory.getOWLClass(IRI.create("http://www.le.ac.uk/travelAgencyOntology.owl#Activity"));

    /* ***************************************************
     * Class http://www.le.ac.uk/travelAgencyOntology.owl#Adventure
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ADVENTURE.<p>
     * 
     */
    public static final OWLClass CLASS_ADVENTURE = factory.getOWLClass(IRI.create("http://www.le.ac.uk/travelAgencyOntology.owl#Adventure"));

    /* ***************************************************
     * Class http://www.le.ac.uk/travelAgencyOntology.owl#Attraction
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ATTRACTION.<p>
     * 
     */
    public static final OWLClass CLASS_ATTRACTION = factory.getOWLClass(IRI.create("http://www.le.ac.uk/travelAgencyOntology.owl#Attraction"));

    /* ***************************************************
     * Class http://www.le.ac.uk/travelAgencyOntology.owl#BnB
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BNB.<p>
     * 
     */
    public static final OWLClass CLASS_BNB = factory.getOWLClass(IRI.create("http://www.le.ac.uk/travelAgencyOntology.owl#BnB"));

    /* ***************************************************
     * Class http://www.le.ac.uk/travelAgencyOntology.owl#Budget
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BUDGET.<p>
     * 
     */
    public static final OWLClass CLASS_BUDGET = factory.getOWLClass(IRI.create("http://www.le.ac.uk/travelAgencyOntology.owl#Budget"));

    /* ***************************************************
     * Class http://www.le.ac.uk/travelAgencyOntology.owl#Bushcraft
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BUSHCRAFT.<p>
     * 
     */
    public static final OWLClass CLASS_BUSHCRAFT = factory.getOWLClass(IRI.create("http://www.le.ac.uk/travelAgencyOntology.owl#Bushcraft"));

    /* ***************************************************
     * Class http://www.le.ac.uk/travelAgencyOntology.owl#City
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CITY.<p>
     * 
     */
    public static final OWLClass CLASS_CITY = factory.getOWLClass(IRI.create("http://www.le.ac.uk/travelAgencyOntology.owl#City"));

    /* ***************************************************
     * Class http://www.le.ac.uk/travelAgencyOntology.owl#Customer
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CUSTOMER.<p>
     * 
     */
    public static final OWLClass CLASS_CUSTOMER = factory.getOWLClass(IRI.create("http://www.le.ac.uk/travelAgencyOntology.owl#Customer"));

    /* ***************************************************
     * Class http://www.le.ac.uk/travelAgencyOntology.owl#Customer_Type
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CUSTOMER_TYPE.<p>
     * 
     */
    public static final OWLClass CLASS_CUSTOMER_TYPE = factory.getOWLClass(IRI.create("http://www.le.ac.uk/travelAgencyOntology.owl#Customer_Type"));

    /* ***************************************************
     * Class http://www.le.ac.uk/travelAgencyOntology.owl#Fishing
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class FISHING.<p>
     * 
     */
    public static final OWLClass CLASS_FISHING = factory.getOWLClass(IRI.create("http://www.le.ac.uk/travelAgencyOntology.owl#Fishing"));

    /* ***************************************************
     * Class http://www.le.ac.uk/travelAgencyOntology.owl#GuidedTour
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class GUIDEDTOUR.<p>
     * 
     */
    public static final OWLClass CLASS_GUIDEDTOUR = factory.getOWLClass(IRI.create("http://www.le.ac.uk/travelAgencyOntology.owl#GuidedTour"));

    /* ***************************************************
     * Class http://www.le.ac.uk/travelAgencyOntology.owl#Hotel
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HOTEL.<p>
     * 
     */
    public static final OWLClass CLASS_HOTEL = factory.getOWLClass(IRI.create("http://www.le.ac.uk/travelAgencyOntology.owl#Hotel"));

    /* ***************************************************
     * Class http://www.le.ac.uk/travelAgencyOntology.owl#Monument
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MONUMENT.<p>
     * 
     */
    public static final OWLClass CLASS_MONUMENT = factory.getOWLClass(IRI.create("http://www.le.ac.uk/travelAgencyOntology.owl#Monument"));

    /* ***************************************************
     * Class http://www.le.ac.uk/travelAgencyOntology.owl#Package
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PACKAGE.<p>
     * 
     */
    public static final OWLClass CLASS_PACKAGE = factory.getOWLClass(IRI.create("http://www.le.ac.uk/travelAgencyOntology.owl#Package"));

    /* ***************************************************
     * Class http://www.le.ac.uk/travelAgencyOntology.owl#Person
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PERSON.<p>
     * 
     */
    public static final OWLClass CLASS_PERSON = factory.getOWLClass(IRI.create("http://www.le.ac.uk/travelAgencyOntology.owl#Person"));

    /* ***************************************************
     * Class http://www.le.ac.uk/travelAgencyOntology.owl#Place
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PLACE.<p>
     * 
     */
    public static final OWLClass CLASS_PLACE = factory.getOWLClass(IRI.create("http://www.le.ac.uk/travelAgencyOntology.owl#Place"));

    /* ***************************************************
     * Class http://www.le.ac.uk/travelAgencyOntology.owl#Rating
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class RATING.<p>
     * 
     */
    public static final OWLClass CLASS_RATING = factory.getOWLClass(IRI.create("http://www.le.ac.uk/travelAgencyOntology.owl#Rating"));

    /* ***************************************************
     * Object Property http://www.le.ac.uk/travelAgencyOntology.owl#Incoporate
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property INCOPORATE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_INCOPORATE = factory.getOWLObjectProperty(IRI.create("http://www.le.ac.uk/travelAgencyOntology.owl#Incoporate"));

    /* ***************************************************
     * Object Property http://www.le.ac.uk/travelAgencyOntology.owl#canPay
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property CANPAY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_CANPAY = factory.getOWLObjectProperty(IRI.create("http://www.le.ac.uk/travelAgencyOntology.owl#canPay"));

    /* ***************************************************
     * Object Property http://www.le.ac.uk/travelAgencyOntology.owl#categorizedBy
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property CATEGORIZEDBY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_CATEGORIZEDBY = factory.getOWLObjectProperty(IRI.create("http://www.le.ac.uk/travelAgencyOntology.owl#categorizedBy"));

    /* ***************************************************
     * Object Property http://www.le.ac.uk/travelAgencyOntology.owl#consistof
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property CONSISTOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_CONSISTOF = factory.getOWLObjectProperty(IRI.create("http://www.le.ac.uk/travelAgencyOntology.owl#consistof"));

    /* ***************************************************
     * Object Property http://www.le.ac.uk/travelAgencyOntology.owl#hasAvaliable
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASAVALIABLE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASAVALIABLE = factory.getOWLObjectProperty(IRI.create("http://www.le.ac.uk/travelAgencyOntology.owl#hasAvaliable"));

    /* ***************************************************
     * Object Property http://www.le.ac.uk/travelAgencyOntology.owl#hasRating
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASRATING.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASRATING = factory.getOWLObjectProperty(IRI.create("http://www.le.ac.uk/travelAgencyOntology.owl#hasRating"));

    /* ***************************************************
     * Object Property http://www.le.ac.uk/travelAgencyOntology.owl#hasToDo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASTODO.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASTODO = factory.getOWLObjectProperty(IRI.create("http://www.le.ac.uk/travelAgencyOntology.owl#hasToDo"));

    /* ***************************************************
     * Object Property http://www.le.ac.uk/travelAgencyOntology.owl#isCategorized
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISCATEGORIZED.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISCATEGORIZED = factory.getOWLObjectProperty(IRI.create("http://www.le.ac.uk/travelAgencyOntology.owl#isCategorized"));

    /* ***************************************************
     * Object Property http://www.le.ac.uk/travelAgencyOntology.owl#isIncluded
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISINCLUDED.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISINCLUDED = factory.getOWLObjectProperty(IRI.create("http://www.le.ac.uk/travelAgencyOntology.owl#isIncluded"));

    /* ***************************************************
     * Object Property http://www.le.ac.uk/travelAgencyOntology.owl#recommend
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property RECOMMEND.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_RECOMMEND = factory.getOWLObjectProperty(IRI.create("http://www.le.ac.uk/travelAgencyOntology.owl#recommend"));

    /* ***************************************************
     * Object Property http://www.le.ac.uk/travelAgencyOntology.owl#reserve
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property RESERVE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_RESERVE = factory.getOWLObjectProperty(IRI.create("http://www.le.ac.uk/travelAgencyOntology.owl#reserve"));

    /* ***************************************************
     * Object Property http://www.le.ac.uk/travelAgencyOntology.owl#select
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property SELECTS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_SELECT = factory.getOWLObjectProperty(IRI.create("http://www.le.ac.uk/travelAgencyOntology.owl#select"));

    /* ***************************************************
     * Object Property http://www.le.ac.uk/travelAgencyOntology.owl#situatedIn
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property SITUATEDIN.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_SITUATEDIN = factory.getOWLObjectProperty(IRI.create("http://www.le.ac.uk/travelAgencyOntology.owl#situatedIn"));

    /* ***************************************************
     * Object Property http://www.le.ac.uk/travelAgencyOntology.owl#suitableFor
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property SUITABLEFOR.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_SUITABLEFOR = factory.getOWLObjectProperty(IRI.create("http://www.le.ac.uk/travelAgencyOntology.owl#suitableFor"));

    /* ***************************************************
     * Object Property http://www.le.ac.uk/travelAgencyOntology.owl#toVisit
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property TOVISIT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_TOVISIT = factory.getOWLObjectProperty(IRI.create("http://www.le.ac.uk/travelAgencyOntology.owl#toVisit"));

    /* ***************************************************
     * Data Property http://www.le.ac.uk/travelAgencyOntology.owl#Acc_Avalibility
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property ACC_AVALIBILITY.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_ACC_AVALIBILITY = factory.getOWLDataProperty(IRI.create("http://www.le.ac.uk/travelAgencyOntology.owl#Acc_Avalibility"));

    /* ***************************************************
     * Data Property http://www.le.ac.uk/travelAgencyOntology.owl#Acc_ID
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property ACC_ID.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_ACC_ID = factory.getOWLDataProperty(IRI.create("http://www.le.ac.uk/travelAgencyOntology.owl#Acc_ID"));

    /* ***************************************************
     * Data Property http://www.le.ac.uk/travelAgencyOntology.owl#Acc_Location
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property ACC_LOCATION.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_ACC_LOCATION = factory.getOWLDataProperty(IRI.create("http://www.le.ac.uk/travelAgencyOntology.owl#Acc_Location"));

    /* ***************************************************
     * Data Property http://www.le.ac.uk/travelAgencyOntology.owl#Acc_Name
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property ACC_NAME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_ACC_NAME = factory.getOWLDataProperty(IRI.create("http://www.le.ac.uk/travelAgencyOntology.owl#Acc_Name"));

    /* ***************************************************
     * Data Property http://www.le.ac.uk/travelAgencyOntology.owl#Acc_ProvidesBreakfast
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property ACC_PROVIDESBREAKFAST.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_ACC_PROVIDESBREAKFAST = factory.getOWLDataProperty(IRI.create("http://www.le.ac.uk/travelAgencyOntology.owl#Acc_ProvidesBreakfast"));

    /* ***************************************************
     * Data Property http://www.le.ac.uk/travelAgencyOntology.owl#Activity_Mode
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property ACTIVITY_MODE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_ACTIVITY_MODE = factory.getOWLDataProperty(IRI.create("http://www.le.ac.uk/travelAgencyOntology.owl#Activity_Mode"));

    /* ***************************************************
     * Data Property http://www.le.ac.uk/travelAgencyOntology.owl#Activity_Name
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property ACTIVITY_NAME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_ACTIVITY_NAME = factory.getOWLDataProperty(IRI.create("http://www.le.ac.uk/travelAgencyOntology.owl#Activity_Name"));

    /* ***************************************************
     * Data Property http://www.le.ac.uk/travelAgencyOntology.owl#Attraction_Location
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property ATTRACTION_LOCATION.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_ATTRACTION_LOCATION = factory.getOWLDataProperty(IRI.create("http://www.le.ac.uk/travelAgencyOntology.owl#Attraction_Location"));

    /* ***************************************************
     * Data Property http://www.le.ac.uk/travelAgencyOntology.owl#Attraction_Name
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property ATTRACTION_NAME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_ATTRACTION_NAME = factory.getOWLDataProperty(IRI.create("http://www.le.ac.uk/travelAgencyOntology.owl#Attraction_Name"));

    /* ***************************************************
     * Data Property http://www.le.ac.uk/travelAgencyOntology.owl#City_ID
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property CITY_ID.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_CITY_ID = factory.getOWLDataProperty(IRI.create("http://www.le.ac.uk/travelAgencyOntology.owl#City_ID"));

    /* ***************************************************
     * Data Property http://www.le.ac.uk/travelAgencyOntology.owl#City_Name
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property CITY_NAME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_CITY_NAME = factory.getOWLDataProperty(IRI.create("http://www.le.ac.uk/travelAgencyOntology.owl#City_Name"));

    /* ***************************************************
     * Data Property http://www.le.ac.uk/travelAgencyOntology.owl#City_Type
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property CITY_TYPE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_CITY_TYPE = factory.getOWLDataProperty(IRI.create("http://www.le.ac.uk/travelAgencyOntology.owl#City_Type"));

    /* ***************************************************
     * Data Property http://www.le.ac.uk/travelAgencyOntology.owl#Cust_ID
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property CUST_ID.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_CUST_ID = factory.getOWLDataProperty(IRI.create("http://www.le.ac.uk/travelAgencyOntology.owl#Cust_ID"));

    /* ***************************************************
     * Data Property http://www.le.ac.uk/travelAgencyOntology.owl#GT_Details
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property GT_DETAILS.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_GT_DETAILS = factory.getOWLDataProperty(IRI.create("http://www.le.ac.uk/travelAgencyOntology.owl#GT_Details"));

    /* ***************************************************
     * Data Property http://www.le.ac.uk/travelAgencyOntology.owl#GT_ID
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property GT_ID.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_GT_ID = factory.getOWLDataProperty(IRI.create("http://www.le.ac.uk/travelAgencyOntology.owl#GT_ID"));

    /* ***************************************************
     * Data Property http://www.le.ac.uk/travelAgencyOntology.owl#GT_Location
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property GT_LOCATION.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_GT_LOCATION = factory.getOWLDataProperty(IRI.create("http://www.le.ac.uk/travelAgencyOntology.owl#GT_Location"));

    /* ***************************************************
     * Data Property http://www.le.ac.uk/travelAgencyOntology.owl#GT_MultiLocations
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property GT_MULTILOCATIONS.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_GT_MULTILOCATIONS = factory.getOWLDataProperty(IRI.create("http://www.le.ac.uk/travelAgencyOntology.owl#GT_MultiLocations"));

    /* ***************************************************
     * Data Property http://www.le.ac.uk/travelAgencyOntology.owl#GT_Timing
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property GT_TIMING.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_GT_TIMING = factory.getOWLDataProperty(IRI.create("http://www.le.ac.uk/travelAgencyOntology.owl#GT_Timing"));

    /* ***************************************************
     * Data Property http://www.le.ac.uk/travelAgencyOntology.owl#Person_Gender
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property PERSON_GENDER.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_PERSON_GENDER = factory.getOWLDataProperty(IRI.create("http://www.le.ac.uk/travelAgencyOntology.owl#Person_Gender"));

    /* ***************************************************
     * Data Property http://www.le.ac.uk/travelAgencyOntology.owl#Person_Name
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property PERSON_NAME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_PERSON_NAME = factory.getOWLDataProperty(IRI.create("http://www.le.ac.uk/travelAgencyOntology.owl#Person_Name"));

    /* ***************************************************
     * Data Property http://www.le.ac.uk/travelAgencyOntology.owl#Person_dob
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property PERSON_DOB.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_PERSON_DOB = factory.getOWLDataProperty(IRI.create("http://www.le.ac.uk/travelAgencyOntology.owl#Person_dob"));

    /* ***************************************************
     * Data Property http://www.le.ac.uk/travelAgencyOntology.owl#Pkg_Avalibility
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property PKG_AVALIBILITY.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_PKG_AVALIBILITY = factory.getOWLDataProperty(IRI.create("http://www.le.ac.uk/travelAgencyOntology.owl#Pkg_Avalibility"));

    /* ***************************************************
     * Data Property http://www.le.ac.uk/travelAgencyOntology.owl#Pkg_Detail
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property PKG_DETAIL.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_PKG_DETAIL = factory.getOWLDataProperty(IRI.create("http://www.le.ac.uk/travelAgencyOntology.owl#Pkg_Detail"));

    /* ***************************************************
     * Data Property http://www.le.ac.uk/travelAgencyOntology.owl#Pkg_Duration
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property PKG_DURATION.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_PKG_DURATION = factory.getOWLDataProperty(IRI.create("http://www.le.ac.uk/travelAgencyOntology.owl#Pkg_Duration"));

    /* ***************************************************
     * Data Property http://www.le.ac.uk/travelAgencyOntology.owl#Pkg_GuidedTour
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property PKG_GUIDEDTOUR.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_PKG_GUIDEDTOUR = factory.getOWLDataProperty(IRI.create("http://www.le.ac.uk/travelAgencyOntology.owl#Pkg_GuidedTour"));

    /* ***************************************************
     * Data Property http://www.le.ac.uk/travelAgencyOntology.owl#Pkg_ID
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property PKG_ID.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_PKG_ID = factory.getOWLDataProperty(IRI.create("http://www.le.ac.uk/travelAgencyOntology.owl#Pkg_ID"));

    /* ***************************************************
     * Data Property http://www.le.ac.uk/travelAgencyOntology.owl#Pkg_budget
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property PKG_BUDGET.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_PKG_BUDGET = factory.getOWLDataProperty(IRI.create("http://www.le.ac.uk/travelAgencyOntology.owl#Pkg_budget"));

    /* ***************************************************
     * Data Property http://www.le.ac.uk/travelAgencyOntology.owl#Pkg_type
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property PKG_TYPE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_PKG_TYPE = factory.getOWLDataProperty(IRI.create("http://www.le.ac.uk/travelAgencyOntology.owl#Pkg_type"));


}
