package faa.travel.agency.ontology.impl;

import faa.travel.agency.ontology.classes.*;
import faa.travel.agency.ontology.classes.Package;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultCustomer <br>
 * @version generated on Mon Apr 17 12:31:16 BST 2017 by favina
 */
public class DefaultCustomer extends WrappedIndividualImpl implements Customer {

    public DefaultCustomer(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





    /* ***************************************************
     * Object Property http://www.le.ac.uk/travelAgencyOntology.owl#canPay
     */
     
    public Collection<? extends Package> getCanPay() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_CANPAY,
                                               DefaultPackage.class);
    }

    public boolean hasCanPay() {
	   return !getCanPay().isEmpty();
    }

    public void addCanPay(Package newCanPay) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_CANPAY,
                                       newCanPay);
    }

    public void removeCanPay(Package oldCanPay) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_CANPAY,
                                          oldCanPay);
    }


    /* ***************************************************
     * Object Property http://www.le.ac.uk/travelAgencyOntology.owl#isCategorized
     */
     
    public Collection<? extends Customer_Type> getIsCategorized() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_ISCATEGORIZED,
                                               DefaultCustomer_Type.class);
    }

    public boolean hasIsCategorized() {
	   return !getIsCategorized().isEmpty();
    }

    public void addIsCategorized(Customer_Type newIsCategorized) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_ISCATEGORIZED,
                                       newIsCategorized);
    }

    public void removeIsCategorized(Customer_Type oldIsCategorized) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_ISCATEGORIZED,
                                          oldIsCategorized);
    }


    /* ***************************************************
     * Object Property http://www.le.ac.uk/travelAgencyOntology.owl#reserve
     */
     
    public Collection<? extends Package> getReserve() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_RESERVE,
                                               DefaultPackage.class);
    }

    public boolean hasReserve() {
	   return !getReserve().isEmpty();
    }

    public void addReserve(Package newReserve) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_RESERVE,
                                       newReserve);
    }

    public void removeReserve(Package oldReserve) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_RESERVE,
                                          oldReserve);
    }


    /* ***************************************************
     * Object Property http://www.le.ac.uk/travelAgencyOntology.owl#select
     */
     
    public Collection<? extends City> getSelect() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_SELECT,
                                               DefaultCity.class);
    }

    public boolean hasSelect() {
	   return !getSelect().isEmpty();
    }

    public void addSelect(City newSelect) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_SELECT,
                                       newSelect);
    }

    public void removeSelect(City oldSelect) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_SELECT,
                                          oldSelect);
    }


    /* ***************************************************
     * Data Property http://www.le.ac.uk/travelAgencyOntology.owl#Cust_ID
     */
     
    public Collection<? extends Integer> getCust_ID() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_CUST_ID, Integer.class);
    }

    public boolean hasCust_ID() {
		return !getCust_ID().isEmpty();
    }

    public void addCust_ID(Integer newCust_ID) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_CUST_ID, newCust_ID);
    }

    public void removeCust_ID(Integer oldCust_ID) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_CUST_ID, oldCust_ID);
    }


    /* ***************************************************
     * Data Property http://www.le.ac.uk/travelAgencyOntology.owl#Person_Gender
     */
     
    public Collection<? extends String> getPerson_Gender() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_PERSON_GENDER, String.class);
    }

    public boolean hasPerson_Gender() {
		return !getPerson_Gender().isEmpty();
    }

    public void addPerson_Gender(String newPerson_Gender) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_PERSON_GENDER, newPerson_Gender);
    }

    public void removePerson_Gender(String oldPerson_Gender) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_PERSON_GENDER, oldPerson_Gender);
    }


    /* ***************************************************
     * Data Property http://www.le.ac.uk/travelAgencyOntology.owl#Person_Name
     */
     
    public Collection<? extends String> getPerson_Name() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_PERSON_NAME, String.class);
    }

    public boolean hasPerson_Name() {
		return !getPerson_Name().isEmpty();
    }

    public void addPerson_Name(String newPerson_Name) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_PERSON_NAME, newPerson_Name);
    }

    public void removePerson_Name(String oldPerson_Name) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_PERSON_NAME, oldPerson_Name);
    }


    /* ***************************************************
     * Data Property http://www.le.ac.uk/travelAgencyOntology.owl#Person_dob
     */
     
    public Collection<? extends String> getPerson_dob() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_PERSON_DOB, String.class);
    }

    public boolean hasPerson_dob() {
		return !getPerson_dob().isEmpty();
    }

    public void addPerson_dob(String newPerson_dob) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_PERSON_DOB, newPerson_dob);
    }

    public void removePerson_dob(String oldPerson_dob) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_PERSON_DOB, oldPerson_dob);
    }


}
