package faa.travel.agency.ontology.impl;

import faa.travel.agency.ontology.classes.*;
import faa.travel.agency.ontology.classes.Package;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultGuidedTour <br>
 * @version generated on Mon Apr 17 12:31:16 BST 2017 by favina
 */
public class DefaultGuidedTour extends WrappedIndividualImpl implements GuidedTour {

    public DefaultGuidedTour(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





    /* ***************************************************
     * Object Property http://www.le.ac.uk/travelAgencyOntology.owl#consistof
     */
     
    public Collection<? extends Place> getConsistof() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_CONSISTOF,
                                               DefaultPlace.class);
    }

    public boolean hasConsistof() {
	   return !getConsistof().isEmpty();
    }

    public void addConsistof(Place newConsistof) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_CONSISTOF,
                                       newConsistof);
    }

    public void removeConsistof(Place oldConsistof) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_CONSISTOF,
                                          oldConsistof);
    }


    /* ***************************************************
     * Object Property http://www.le.ac.uk/travelAgencyOntology.owl#isIncluded
     */
     
    public Collection<? extends Package> getIsIncluded() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_ISINCLUDED,
                                               DefaultPackage.class);
    }

    public boolean hasIsIncluded() {
	   return !getIsIncluded().isEmpty();
    }

    public void addIsIncluded(Package newIsIncluded) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_ISINCLUDED,
                                       newIsIncluded);
    }

    public void removeIsIncluded(Package oldIsIncluded) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_ISINCLUDED,
                                          oldIsIncluded);
    }


    /* ***************************************************
     * Data Property http://www.le.ac.uk/travelAgencyOntology.owl#GT_Details
     */
     
    public Collection<? extends String> getGT_Details() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_GT_DETAILS, String.class);
    }

    public boolean hasGT_Details() {
		return !getGT_Details().isEmpty();
    }

    public void addGT_Details(String newGT_Details) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_GT_DETAILS, newGT_Details);
    }

    public void removeGT_Details(String oldGT_Details) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_GT_DETAILS, oldGT_Details);
    }


    /* ***************************************************
     * Data Property http://www.le.ac.uk/travelAgencyOntology.owl#GT_ID
     */
     
    public Collection<? extends Integer> getGT_ID() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_GT_ID, Integer.class);
    }

    public boolean hasGT_ID() {
		return !getGT_ID().isEmpty();
    }

    public void addGT_ID(Integer newGT_ID) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_GT_ID, newGT_ID);
    }

    public void removeGT_ID(Integer oldGT_ID) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_GT_ID, oldGT_ID);
    }


    /* ***************************************************
     * Data Property http://www.le.ac.uk/travelAgencyOntology.owl#GT_Location
     */
     
    public Collection<? extends String> getGT_Location() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_GT_LOCATION, String.class);
    }

    public boolean hasGT_Location() {
		return !getGT_Location().isEmpty();
    }

    public void addGT_Location(String newGT_Location) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_GT_LOCATION, newGT_Location);
    }

    public void removeGT_Location(String oldGT_Location) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_GT_LOCATION, oldGT_Location);
    }


    /* ***************************************************
     * Data Property http://www.le.ac.uk/travelAgencyOntology.owl#GT_MultiLocations
     */
     
    public Collection<? extends Boolean> getGT_MultiLocations() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_GT_MULTILOCATIONS, Boolean.class);
    }

    public boolean hasGT_MultiLocations() {
		return !getGT_MultiLocations().isEmpty();
    }

    public void addGT_MultiLocations(Boolean newGT_MultiLocations) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_GT_MULTILOCATIONS, newGT_MultiLocations);
    }

    public void removeGT_MultiLocations(Boolean oldGT_MultiLocations) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_GT_MULTILOCATIONS, oldGT_MultiLocations);
    }


    /* ***************************************************
     * Data Property http://www.le.ac.uk/travelAgencyOntology.owl#GT_Timing
     */
     
    public Collection<? extends Integer> getGT_Timing() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_GT_TIMING, Integer.class);
    }

    public boolean hasGT_Timing() {
		return !getGT_Timing().isEmpty();
    }

    public void addGT_Timing(Integer newGT_Timing) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_GT_TIMING, newGT_Timing);
    }

    public void removeGT_Timing(Integer oldGT_Timing) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_GT_TIMING, oldGT_Timing);
    }


}
